name: Deploy to staging

on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: SSH and deploy
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          ssh ubuntu@13.233.117.166 << 'EOF'
            set -e
            cd bms2
            git pull origin main
            export PATH=/home/ubuntu/.nvm/versions/node/v24.11.1/bin:$PATH
            npm install -g pnpm
            pnpm install
            pnpm run build
            pm2 restart web
            pm2 restart http-server
            pm2 restart ws-server
          EOF
